apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alstom
  template:
    metadata:
      labels:
        app: alstom
    spec:
      containers:
        - name: productservice
          image: redis
